name: CI

#on:
#  push:
#    branches: ["main"]
  
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one line script
        run: echo Hello, world
      - name: wait 100 sec
        run: sleep 100
