name: CI_NEW

on:
  workflow_dispatch:

jobs:
  dbt_ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: check python version
        run: python --version
      - name: Install dbt snowflake
        run: pip install dbt-snowflake
      - name: Install python deps
        run: dbt deps
      - name: Run dbt test
        run: dbt test --profiles-dir ./
      - name: dbt run
        run: dbt run --profiles-dir ./
